# -*- coding: utf-8 -*-
"""display.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12tlLVSDhdHpqQ1CHVFGrdJApBviNcxdA

# TMDB 결과 출력 (포스터 포함)
"""

def display_tmdb_results(movies):
    if not movies:
        print("❌ 해당 장르의 추천 영화가 없습니다.")
        return
    for m in movies:
        title = m.get('title')
        date = m.get('release_date')
        overview = m.get('overview') or '내용 없음'
        poster_path = m.get('poster_path')
        poster_url = f"https://image.tmdb.org/t/p/w500{poster_path}" if poster_path else None

        print(f"\n🎬 제목: {title}")
        print(f"📅 개봉일: {date}")
        print(f"📝 개요: {overview}")
        if poster_url:
            display(Image(url=poster_url, width=250))
        print("-" * 60)

"""# uNoGS 결과 출력 (포스터 + 번역 포함)"""

def display_unogs_results(results):
    if not results:
        print("❌ 추천 결과가 없습니다. 조건을 다시 확인해 보세요.")
        return
    for item in results:
        title = item.get('title')
        year = item.get('year')
        synopsis = item.get('synopsis', '')
        translated = translator.translate(synopsis, dest='ko').text if synopsis else '내용 없음'
        img_url = item.get('img')

        print(f"\n🎬 제목: {title} ({year})")
        print(f"📝 개요: {translated}")
        if img_url:
            display(Image(url=img_url, width=250))
        print("-" * 60)