# -*- coding: utf-8 -*-
"""tmdb_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2zkJTOz3WzjHy3Gl9mp1DViKGI2J45O

# TMDB 장르 목록 조회
"""

TMDB_API_KEY = 'cba511a5cd8d9c9fdb4d7297c1e555bd'

def get_tmdb_genres():
    url = "https://api.themoviedb.org/3/genre/movie/list"
    params = {'api_key': TMDB_API_KEY, 'language': 'ko-KR'}
    response = requests.get(url, params=params)
    genres = response.json().get('genres', [])
    return {g['name']: g['id'] for g in genres}

"""# TMDB 인기 영화 + 장르 필터"""

def fetch_tmdb_movies_by_genre(selected_genre_id):
    url = "https://api.themoviedb.org/3/movie/popular"
    params = {'api_key': TMDB_API_KEY, 'language': 'ko-KR'}
    response = requests.get(url, params=params)
    results = response.json().get("results", [])
    if selected_genre_id:
        results = [m for m in results if selected_genre_id in m.get('genre_ids', [])]
    return results