# -*- coding: utf-8 -*-
"""unogs_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ztu5gRaV_ygVney5jwpzyT__3POXDG2a
"""

UNOGS_API_KEY = 'e232918b50msh15dc890c9e18b2fp181942jsn078e62dc0b4b'
UNOGS_HOST = 'unogsng.p.rapidapi.com'

"""# 번역"""

!pip install requests googletrans==3.1.0a0
from googletrans import Translator
translator = Translator()

"""# uNoGS 넷플릭스 콘텐츠 추천"""

UNOGS_GENRES = [
    'action', 'adventure', 'animation', 'comedy', 'crime',
    'documentary', 'drama', 'family', 'fantasy', 'horror',
    'romance', 'sci-fi', 'thriller', 'war'
]


def fetch_unogs_recommendations(genre, year, limit=10):
    url = f"https://{UNOGS_HOST}/search"
    headers = {
        "X-RapidAPI-Key": UNOGS_API_KEY,
        "X-RapidAPI-Host": UNOGS_HOST
    }
    params = {
        "query": genre,
        "start_year": year,
        "countrylist": "78",  # 한국
        "limit": 50
    }
    response = requests.get(url, headers=headers, params=params)
    response.raise_for_status()
    all_results = response.json().get("results", [])
    final_results = [item for item in all_results if item.get('year') and int(item['year']) >= year]
    return final_results[:limit]