# -*- coding: utf-8 -*-
"""Weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADd5FDw71ubJiBTB8Djy_0ia9UFtU-eB

## 날씨 데이터 불러오기

OpenWeatherMap API를 활용하여 특정 도시의 실시간 날씨 정보를 가져온다. requests 라이브러리로 API 서버에 날씨 정보를 요청하고, 응답으로 받은 JSON 형식의 데이터를 json 라이브러리로 파이썬 딕셔너리로 변환한 뒤, 필요한 날씨 정보(온도, 습도, 현재 온도 등)를 추출하여 화면에 표시한다.
"""

import requests
import json

city = "Seoul"
apikey = "3854b1d0a01aeb63f5955b5c86dd8320"
lang = "kr"

api = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={apikey}&lang={lang}&units=metric"

result = requests.get(api)
data = json.loads(result.text)

print(data["name"],"의 날씨입니다.")
print("날씨는", data["weather"][0]["description"], "입니다.")
print("현재 온도는", data["main"]["temp"], "입니다.")
print("하지만 체감 온도는", data["main"]["feels_like"], "입니다.")
print("최저 기온은", data["main"]["temp_min"], "입니다.")
print("최고 기온은", data["main"]["temp_max"], "입니다.")
print("습도는", data["main"]["humidity"], "입니다.")

